# Generated by Django 5.1 on 2024-08-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clients_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='definition',
            field=models.TextField(null=True),
        ),
    ]
