# Generated by Django 5.1 on 2024-08-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clients_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish')], default='pb', max_length=4),
        ),
        migrations.AddField(
            model_name='faqs',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish')], default='pb', max_length=4),
        ),
    ]
